site_name: Mlego Notes
site_url: https://mlego.elena.space
site_dir: public
docs_dir: ./notes
repo_url: https://gitlab.com/m-lego/m65
copyright: alin m elena

theme:
  name: material
  palette:
    scheme: slate
    primary: teal
    accent: lime

# Extensions
markdown_extensions:
    - footnotes
    - attr_list
    - pymdownx.highlight
    - pymdownx.superfences
    - pymdownx.details
    - pymdownx.magiclink
    - pymdownx.tasklist
    - pymdownx.emoji
    - admonition
    - toc:
      permalink: True

plugins:
  - search
  - roamlinks
