site_name: mlego motes
site_url: https://mlego.elena.space
site_dir: public
docs_dir: ./notes
repo_url: https://gitlab.com/m-lego/m65
copyright: Ⓒ 2017-2022 alin m elena
site_author: alin m elena
site_description: set of notes on mlego keyboards

theme:
  name: material
  palette:
    scheme: slate
    primary: teal
    accent: lime
  include_sidebar: false


# Extensions
markdown_extensions:
    - footnotes
    - attr_list
    - pymdownx.highlight
    - pymdownx.superfences
    - pymdownx.details
    - pymdownx.magiclink
    - pymdownx.tasklist
    - pymdownx.emoji
    - admonition
    - toc:
        permalink: True

plugins:
  - search
  - roamlinks
  - social
