site_name: mlego notes
site_url: https://mlego.elena.space
site_dir: public
docs_dir: ./notes
repo_url: https://gitlab.com/m-lego/m65
copyright: Ⓒ 2017-2022 alin m elena
site_author: alin m elena
site_description: set of notes on mlego keyboards

theme:
  name: material
  palette:
    scheme: slate
    primary: teal
    accent: lime
  language: en
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.expand

# Extensions
markdown_extensions:
    - footnotes
    - attr_list
    - pymdownx.highlight
    - pymdownx.superfences
    - pymdownx.details
    - pymdownx.magiclink
    - pymdownx.emoji
    - admonition
    - pymdownx.tabbed:
        alternate_style: True
    - pymdownx.tasklist:
        custom_checkbox: True
    - toc:
        permalink: True

plugins:
  - search
  - roamlinks

nav:
    - Home: index.md
    - Keyboards:
      - m65: m65.md
      - m60: m60.md

